apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
data:
  # fsa-pieterr-psql.postgres.database.azure.com -> fsaadmin -> P@ssword12345
  #
  db_username: ZnNhYWRtaW4=
  db_password: UEBzc3dvcmQxMjM0NQ==
  db_url: ZnNhYmVsYW4tcHNxbC5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb20=

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: app
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
data:
  # admin -> admin
  kc_username: YWRtaW4=
  kc_password: YWRtaW4=

---

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: infra
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
data:
  runner-registration-token: ""
  runner-token: Z2xydC16Vl9ma1d6OHlzZnRCbXk4ZlhkRw==